#!/usr/bin/env python3
import itertools

def q1(sentence):
    '''
    Given a string of multiple words separated by single spaces,
    return a new string with the sentence reversed. The words
    themselves should remain as they are. For example, given
    'it is accepted as a masterpiece on strategy', the returned
    string should be 'strategy on masterpiece a as accepted is it'.


    ***professor's answer***

    words = sentence.split()
    rev = []
    for i in range(len(words)-1,-1,-1):
        rev.append(words[i])
    return ' '.join(rev)

    OR

    return ' '.join(reversed(sentence.split()))

    '''
    lst = sentence.split()
    new_lst = ' '.join(list(reversed(lst)))
    return new_lst
    pass

def q2(n):
    '''
    Given a positive integer, return its string representation with
    commas seperating groups of 3 digits. For example, given 65535
    the returned string should be '65,535'.

    ***professor's answer***


    '''
    num = "{:,}".format(n)
    return num

    pass

def q3(lst0, lst1):
    '''
    Given two lists of integers, return a sorted list that contains
    all integers from both lists in descending order. For example,
    given [3,4,9] and [8,1,5] the returned list should be [9,8,5,4,3,1].
    The returned list may contain duplicates.

    ***professor's answer***

    return sorted(lst0+lst1, reverse=True)
    '''
    num_lst = lst0 + lst1
    num_lst.sort(reverse=True)
    return num_lst
    pass

def q4(s1,s2,s3):
    '''
    Given 3 scores in the range [0-100] inclusive, return 'GO' if
    the average score is greater than 50. Otherwise return 'NOGO'.

    ***professor's answer***
    avg = (s1+s2+s3) / 3.0
    if avg > 50.0
        return 'GO'
    else
        return 'NOGO'

    '''
    scores = s1 + s2 + s3
    avg = scores/3
    if avg > 50:
        return 'GO'
    else:
        return 'NOGO'

    pass

def q5(integer, limit):
    '''
    Given an integer and limit, return a list of even multiples of the
    integer up to and including the limit. For example, if integer==3 and
    limit==30, the returned list should be [0,6,12,18,24,30]. Note, 0 is
    a multiple of any integer except 0 itself.

    ***professor's answer***

    multiples = []
    for i in range(0, limit+1):
        if (i%integer==0) and (i%2==0):
            multiples.append(i)
        return multiples

    OR

    return [i for i in range(limit+1) if (i%integer==0) and (i%2==0)]

    '''
    lst = [0]
    for i in range(integer, limit+1):
        if i % 2 == 0 and i % integer == 0:
            lst.append(i)

    return lst

    pass

def q6(f0, f1):
    '''
    Given two filenames, return a list whose elements consist of line numbers
    for which the two files differ. The first line is considered line 0.
    '''
    with open(f0, 'r') as fin0, open(f1, 'r') as fin1:
        index = 0
        temp = []

        for line in fin0:
            if line != fin1.readline():
                temp.append(index)
            index += 1
    return temp
    pass

def q7(lst):
    '''
    Return the first duplicate value in the given list.
    For example, if given [5,7,9,1,3,7,9,5], the returned value should
    be 7.

    ***professor's answer***

    i did exactly what the professor did

    '''
    seen = set()
    for i in lst:
        if i in seen:
            return i
        seen.add(i)

    pass

def q8(strng):
    '''
    Given a sentence as a string with words being separated by a single space,
    return the length of the shortest word.

    ***professor's answer***

    words = strng.split()
    minlen = len(words[0])
    for word in words:
        if len(word) < minlen:
            minlen = len(word)
    return minlen

    OR

    return chr(int(''.join([c for c in strng if c.isdigit()])))

    '''
    temp = strng.split()
    res = min(len(ele) for ele in temp)
    return res

    pass

def q9(strng):
    '''
    Given an alphanumeric string, return the character whose ascii value
    is that of the integer represenation of all of the digits in the string
    concatenated in the order in which they appear. For example, given
    'hell9oworld7', the returned character should be 'a' which has
    the ascii value of 97.

    ***professor's answer***

    chars = []
    for c in strng:
        if c in strng.isdigits:
            chars.append(c)
        return chr(int(''.join(chars)))

    '''
    lst = []
    for i in strng:
        if i.isdigit():
            lst.append(i)
    final = int(''.join(lst))
    return chr(final)

    pass

def q10(arr):
    '''
    Given a list of positive integers sorted in ascending order, return
    the first non-consecutive value. If all values are consecutive, return
    None. For example, given [1,2,3,4,6,7], the returned value should be 6.

    ***professor's answer***

    for i in range(len(arr)-1):
        if (arr[i+1] - arr[i]) != 1
            return arr[i+1]
        return None
    OR

    return [arr[i] for i in range(len(arr)) if arr[i] - arr[0] != 1][0]

    '''
    prev = arr[0]
    first = None
    for num in arr[1:]:
        if (prev + 1) != num:
            first = num
            break
        prev += 1
    return first
    pass
